### ISSUE TITLE
How to set recycle view as usecache = false

### ISSUE THREAD

**Issue by Ourobolost** [michael-rapp/ChromeLikeTabSwitcher#5] opened 2017-08-18 10:27 UTC
Firstly, I try to develop web browser with this library but I have a problem that if I create new tab which has the same view type of old one that was deleted it will provide old view.
So, I don't know where and how to set this library to create new view every create new tab even it get same view type ( the old tab that contain the view type was deleted).

**Comment by michael-rapp** [comment] 2017-08-18 10:46
When a tab is removed, its view is not deleted, but kept in memory to be reused when adding a tab with the same view type. This is intended behavior and helps to increase performance. Could you please post the code of your Decorator implementation so I can tell what you are eventually doing wrong?

**Comment by anandmahesh** [comment] 2017-10-02 12:23
You need to set viewType different on creation of new tab , you can achieve this with the help of counter and increment this with new Tab added .Intialize counter with value as you required in my case i assigned it value 2 for leaving space for hiostry tab and download view tab
Counter start with zero then in Decorator you can differentiate with the help of switch statement on viewType in both methods OnInflateTab and OnShowTab.
 0 - for history Tab 
1 - for Download Tab
above 1 treat as webView Tabs...etc

**Comment by michael-rapp** [comment] 2017-10-02 17:06
@Ourobolost The root of your problem might be the issue discussed in https://github.com/michael-rapp/ChromeLikeTabSwitcher/issues/6#issuecomment-333592651

Please take a look at it and tell, if the provided solution solves your issue.

**Comment by michael-rapp** [comment] 2017-11-25 23:21
Because there was no feedback to this issue for quite some time, I will close it. If you still have problems feel free to reopen it and provide additional information.

**Closed by michael-rapp** 2017-11-25 23:21 UTC
Labels: question

**Comment by michael-rapp** [comment] 2018-07-27 13:09
I created issue https://github.com/michael-rapp/ChromeLikeTabSwitcher/issues/19 to start a discussion about how to properly use this library together with `WebView`s.
