### ISSUE TITLE
new tab chrome like tab switcher

### ISSUE THREAD

**Issue by ayushnitra** [michael-rapp/ChromeLikeTabSwitcher#29] opened 2020-07-14 06:33 UTC
Sir,
In Tab1 or Tab2 how can we perform click event by click listener(setonClickListener), Please reply me sir It is very nessasry

**Comment by michael-rapp** [comment] 2020-07-14 14:44
Duplicate of #28

**Closed as completed by michael-rapp** 2020-07-14 14:44 UTC
Labels: duplicate, question
