### ISSUE TITLE
Landscape overflow renders incorrectly

### ISSUE THREAD

**Issue by milek** [michael-rapp/ChromeLikeTabSwitcher#3] opened 2017-05-11 10:41 UTC
In landscape mode, (regardless if background is transparent or not) views are not properly rendered. 

![screen shot 2017-05-11 at 12 38 56](https://cloud.githubusercontent.com/assets/61667/25945365/e66814b4-3646-11e7-993b-0ffc7066ead9.png)

Tested on both 0.1.0 and 1.0.0 branches.

**Comment by michael-rapp** [comment] 2017-05-11 12:59
So this does only occur in landscape mode? Maybe you can send me the code of your app as a minimal working example? I never encountered a similar issue and without any code being available it is very hard to reason what is going on there.
 
By the way, the 1.0.0 branch is still under heavy development and cannot be considered stable yet.

**Comment by michael-rapp** [comment] 2017-05-21 20:39
This is just a reminder that I will not be able work on resolving this issue until you've sent me a minimal working example, which allows to reproduce the issue. It would be nice, if you could give me an update on whether the issue still persists.

**Comment by michael-rapp** [comment] 2017-05-22 00:23
Just in case your issue was related to restoring the positions of tabs after orientation changes, please note that version 0.1.2 contains multiple patches regarding that aspect. Please try, if the problem persists.

**Comment by milek** [comment] 2017-05-23 09:24
I'll try to prepare sample application as soon I'll get some time to work on it.

**Comment by michael-rapp** [comment] 2017-05-23 12:42
Okay, thank you.

**Comment by michael-rapp** [comment] 2017-08-22 22:39
Issue will be closed until further information about how to reproduce the problem is available.

**Closed by michael-rapp** 2017-08-22 22:39 UTC
Labels: bug, help wanted

**Comment by milek** [comment] 2017-08-22 23:36
I will forward this ticket to current maintainer of the project @Plukaszuk
